M48
; DRILL file {KiCad 7.0.6} date Tue Oct 31 01:28:27 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-31T01:28:27+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X3.9614Y-3.1982
X4.0795Y-3.1982
T2
X2.8832Y-3.186
X2.8842Y-1.865
X4.315Y-3.187
X4.318Y-1.864
T0
M30
